### PR TITLE
Closes #146 Provide error message for invalid aval_fun

### LINKED ISSUE #146: Bug: No helpful error message if `aval_fun` fails
### What happened?

If the function specified for `aval_fun` causes an error, no helpful error message is provided.

```
> derive_param_bor(
+   adrs,
+   dataset_adsl = adsl,
+   filter_source = PARAMCD == "OVR" & ANL01FL == "Y",
+   source_pd = pd_date,
+   source_datasets = list(adrs = adrs),
+   aval_fun = tibble,
+   reference_date = TRTSDT,
+   ref_start_window = 28,
+   set_values_to = vars(
+     PARAMCD = "BOR",
+     PARAM = "Best Overall Response"
+   )
+ ) %>%
+   filter(PARAMCD == "BOR")
Error in `FUN()`:
! `quo` must be a quosure
Run `rlang::last_error()` to see where the error occurred.
```

### Session Information

_No response_

### Reproducible Example

_No response_

### PR DESCRIPTION
**Pull request by bundfussr**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiralonco/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -0,0 +1,73 @@
+#' Creates `AVAL` from `AVALC` by Calling User Function
+#'
+#' Create `AVAL` from `AVALC` by calling a function provided by the user. If
+#' calling the function fails, the error is catched and a helpful error message
```
Comment (rossfarrugia) [inline R/utils.R:4]: catched -> caught

File: R/utils.R [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+#'   *Permitted Values*: a function
+#'
+#' @details The new variable `AVAL` is set to `aval_fun(AVALC)`.
+#'
+#' @author Stefan Bundfuss
+#'
+#' @returns The input dataset with `AVAL` added
+#'
+#' @keywords utils_catch
+#' @family utils_catch
```
Comment (rossfarrugia) [inline R/utils.R:27]: utils_catch should also be added to man/roxygen/meta.R

**Review by rossfarrugia — CHANGES_REQUESTED** [review]
@bundfussr left some small comments and hope @sgorm123 is ok to double check the code updates

File: R/utils.R (hunk 1 above)
Comment (bundfussr) [reply R/utils.R:4]: Strange that the spelling check passed. If I run it locally, the error is found.

@cicdguy , could you have a look? There is also a warning in the log of the spellcheck. I am not sure if it is expected.

File: R/derive_param_bor.R [hunk 3]
```diff
@@ -475,29 +475,9 @@ derive_param_bor <- function(dataset,
   # aval_fun(AVALC): Execute aval_fun ----
```
Comment (sgorm123) [inline R/derive_param_bor.R:475]: Should the assertions be dropped in the derive functions that check aval_fun(), i.e. assert_function(arg = aval_fun)?

**Comment by sgorm123** [comment]
There are a lot of changes in devel that need to be merged into here @bundfussr, could you do this now and I can re-review?

File: _pkgdown.yml [hunk 4]
```diff
@@ -41,6 +41,10 @@ reference:
  - contents:
    - has_keyword('utils_fil')
```
Comment (sgorm123) [inline _pkgdown.yml:43]: do you think it better we group these all as admiralonco utilities? 

has_keyword('utils_admiralonco')

**Comment by bundfussr** [comment]
@sgorm123 , I am working on it. Should be ready soon.

File: NAMESPACE [hunk 5]
```diff
@@ -1,6 +1,7 @@
 # Generated by roxygen2: do not edit by hand
 
 export(aval_resp)
+export(call_aval_fun)
 export(death_event)
```
Comment (sgorm123) [inline NAMESPACE:5]: I can see this helps us as developers, but should we export this? Or is it convention to expose all?

Comment (bundfussr) [reply NAMESPACE:5]: I would export it because it could be useful for implementing company specific functions.

File: _pkgdown.yml (hunk 4 above)
Comment (rossfarrugia) [reply _pkgdown.yml:43]: i followed admiral core convention here to separate these out on the Reference page. if we end up not having so many for admiralonco though i'd be happy to re-visit later and bundle these altogether if it makes things neater

File: R/derive_param_bor.R (hunk 3 above)
Comment (bundfussr) [reply R/derive_param_bor.R:475]: Yes, good point. I'll remove them.

File: R/utils.R (hunk 2 above)
Comment (bundfussr) [reply R/utils.R:27]: Added

**Review by rossfarrugia — APPROVED** [review]

File: R/utils.R [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+    error = function(cnd) {
+      abort(
+        paste0(
+          "Assigning new AVAL records with aval_fun (`AVAL = aval_fun(AVALC)`) has failed.\n",
+          "Error message:\n  ",
+          cnd
+        )
+      )
+    }
+  )
```
Comment (sgorm123) [inline R/utils.R:72]: Do you think it is worth asserting here (after the try catch) to ensure AVAL is not all missing (it is something I would do)?  It might not error, but the function may not perform as expected.

Comment (sgorm123) [reply R/utils.R:72]: @bundfussr did you not see the comment above?

Comment (bundfussr) [reply R/utils.R:72]: Sorry, I forgot to send my answer:

I would not check on missings because it is not required to populate `AVAL`.

We could check the type of `AVAL` but I would do it in the next release because we want to finish all updates today.

File: R/utils.R (hunk 1 above)
Comment (cicdguy) [reply R/utils.R]: The warning can be ignored.
Apparently `catched` is a word that is defined in the Merriam Webster dictionary: https://www.merriam-webster.com/dictionary/catched
I would have never catched that.

Comment (bundfussr) [reply R/utils.R]: Interesting!
Thanks, @cicdguy
